In [3]:
# =======================================================
# https://numpy.org/devdocs/reference/index.html#
# =======================================================


# 链接数据库，获取数据

print("=== pandas读取数据库 ===")

import pandas as pd
from sqlalchemy import create_engine

USER = "waimai_dq"
PW = "iadCfu8C5xnHcl"
DB_HOST = "10.189.181.21"
DB_PORT = 5002
DB_NAME = "waimai_data_query"

# 用 sqlalchemy 构建数据库连接
connect_info = "mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8".format(USER, PW, DB_HOST, DB_PORT, DB_NAME)
print(connect_info)
# engine = create_engine(connect_info)

# select id, name, git, octo_app_key, bds_mode, plus_id, plus_name, business
sql_cmd_02 = "select id, name, git, octo_app_key, bds_mode, plus_id, plus_name, business from job where octo_app_key != '' limit 10"

print(sql_cmd_02)
# df = pd.read_sql(sql=sql_cmd_02, con=engine, columns=['name', 'octo_app_key', 'bds_mode'])
# print(df)




=== pandas读取数据库 ===
mysql+pymysql://waimai_dq:iadCfu8C5xnHcl@10.189.181.21:5002/waimai_data_query?charset=utf8
select id, name, git, octo_app_key, bds_mode, plus_id, plus_name, business from job where octo_app_key != '' limit 10


In [ ]:
# =======================================================
# https://numpy.org/devdocs/reference/arrays.ndarray.html
# =======================================================


import numpy as np
# N维数组 ndarray

# 一个 ndarray是具有相同类型和大小的项目的（通常是固定大小的）多维容器        shape, dtype
# ndarray可以共享相同的数据; 因此在一个ndarray中进行的更改可能在另一个中可见

x = np.array([[1,2,3],[4,5,6]], np.int32)
type(x)

x.shape     # (2, 3)

x.dtype     # dtype('int32')

# 类似容器操作
x[1,2]      # 6

x           # array([[1, 2, 3],
            #        [4, 5, 6]], dtype=int32)


# 切片 生成数组视图  （ : 表示取当前维度的全部数据）
y = x[:,1]
y           # array([2, 5], dtype=int32)

y[0] = 9
y           # array([9, 5], dtype=int32)

# 此时 x 也已经跟随变动
x           # array([[1, 9, 3],
            #        [4, 5, 6]], dtype=int32)


In [ ]:
# 创建 ndarray -> [以填充方式创建]

# 返回给定形状和类型的新数组，而无需初始化条目。
nda01 = np.empty(3, np.int32)
print(nda01)

# 返回形状和类型与给定数组相同的新数组
nda02 = np.empty_like(nda01)
print(nda02)

# 返回一个二维数组，对角线上有一个，其他地方为零。(k表示第一行第k个元素为1，然后构造三角阵；当k=0时 为单位阵)
nda03 = np.eye(3, k=0)
print(nda03)

# 返回单位方阵，相当于 np.eye(n, k=0)
nda04 = np.identity(5)
print(nda04)

# 返回全部填充1的矩阵
nda05 = np.ones((3,4))
print(nda05)

# 返回全部填充0的矩阵
nda06 = np.zeros((3,4))

print(nda06)

# 返回全部填充 value 的矩阵
nda07 = np.full((3,4), 5)
print(nda07)


In [5]:
import numpy as np

# 创建 ndarray -> [从现有数据创建]

# 根据传入数据创建#
nda08 = np.array([2, 3, 5, 9.2])               # 自动upcast为 float
print(nda08)
nda09 = np.array([[1, 2], [3, 4]])             # 多维
print(nda09)

nda10 = np.array([2,4,6], ndmin=3)              # 指定最小维数
print(nda10)


[2.  3.  5.  9.2]
[[1 2]
 [3 4]]
[[[2 4 6]]]


In [10]:
# np.asarray() 将输入转化为数组

a = [1, 2]
npa11 = np.asarray(a)
print(npa11)

a = np.array([1, 2])
npa11 = np.asarray(a)
print(npa11 is a)           # True

print(issubclass(np.recarray, np.ndarray))      # True


a = np.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(np.recarray)
print(np.asarray(a) is a)               # False
print(np.asanyarray(a) is a)            # True
# 使用 asanyarray 永远 is a


x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
print(type(m))

print('=========')


# copy 数组副本 同  np.array(a, copy=True)  数字深拷贝，对象浅拷贝
x = np.array([1,2,3])
y = x
z = np.copy(x)
x[1] = 100
print(x, y, z)  # y关联变动，但z不变动


# 对象浅拷贝
a = np.array([1, 'm', [2, 3, 4]], dtype=object)
b = np.copy(a)
b[2][0] = 10
print(a, b)

# 真正实现对象深拷贝 使用 copy.deepcopy
import copy

a = np.array([1, 'm', [2, 3, 4]], dtype=object)
c = copy.deepcopy(a)
a[2][0] = 100

print(a, c)         # a c 互不影响

print('====*******====')



# 函数处理得数组
# i,j 代表N维向量 方向向标，必须与后面的维度一致
nda12 = np.fromfunction(lambda i, j: i == j, (3,3), dtype=int)
print(nda12)

print('====*******====')
# 从迭代列表中 构造一维数组
iterable = (x*x for x in range(5))
print(iterable)
nda13 = np.fromiter(iterable, float)
print(nda13)

# 字符串分割数组
nda14 = np.fromstring('1, 2', dtype=int, sep=',')
print(nda14)

# 字符流获取 dtype指定类型
from io import StringIO
d = StringIO("M 21 72\nF 35 58")
nda15 = np.loadtxt(d, dtype={'names': ('gender', 'age', 'weight'),
                             'formats': ('S1', 'i4', 'f4')})
print(nda15)



[1 2]
True
True
False
True
<class 'numpy.matrix'>
[  1 100   3] [  1 100   3] [1 2 3]
[1 'm' list([10, 3, 4])] [1 'm' list([10, 3, 4])]
[1 'm' list([100, 3, 4])] [1 'm' list([2, 3, 4])]
====*******====
[[ True False False]
 [False  True False]
 [False False  True]]
====*******====
<generator object <genexpr> at 0x11a7e4350>
[ 0.  1.  4.  9. 16.]
[1 2]
[(b'M', 21, 72.) (b'F', 35, 58.)]


In [22]:
# 创建 数值范围
# arange 返回给定间隔内的均匀间隔的值
print('-----arange-----')
nda16 = np.arange(0,50,5,dtype=int)
nda17 = np.arange(-3,3,0.5,dtype=int)   # 并不是想要效果，因为这种情况下步长被重置了，应该使用 linespace
nda18 = np.linspace(-3, 3, 6, dtype=int)
print(nda16, nda17, nda18)
# 简单arange 默认左闭右开，步长为1
print(np.arange(0,3))
print(np.arange(4,9))       # [4 5 6 7 8]

# 返回指定间隔内的等间隔数字
print('-----linespace-----')
np.linspace(2.0, 3.0, num=5, retstep=True)
np.linspace(2.0, 3.0, num=5, endpoint=False)
np.linspace(2.0, 3.0, num=5)

# logspace 类同 linespace，只不过间隔是 log 10为底的对数级别 -》 返回数以对数刻度均匀分布。
print(np.logspace(2, 3, 4))     # 2,3 之间 4个数 （2,3 表示10的幂）

# geomspace 返回数字以对数刻度（几何级数）均匀分布
# 略 ...


-----arange-----
[ 0  5 10 15 20 25 30 35 40 45] [-3 -2 -1  0  1  2  3  4  5  6  7  8] [-3 -1  0  0  1  3]
[0 1 2]
[4 5 6 7 8]
-----linespace-----
[ 100.          215.443469    464.15888336 1000.        ]


In [32]:
# 创建矩阵
# diag  提取对角线或构造对角线数组
print('----diag----')
x = np.arange(9).reshape(3,3)
print(x)

print(np.diag(x))           # 提取对角线元素 -> [0,4,8]
print(np.diag(x, k=1))      # [1,5]
print(np.diag(x, k=-1))      # [3,7]

np.diag(np.diag(x))         # 入参为数组 则构造为 对应的 主对角矩阵


# 三角矩阵构造
print('----tri----')
np.tri(3, 5, 2, dtype=int)  # 3行5列元素为1的矩阵，k=2
np.tri(4,4)                 # 元素全为1的下三角4阶方阵

# 截取下三角矩阵 tril  (上三角 triu)
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)   # k = -1, 保留下三角部分
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)   # k = -1, 保留上三角部分




----diag----
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[1 5]
[3 7]
----tri----


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])