In [8]:
# =============================
# 数组基本操作
# https://www.numpy.org.cn/reference/routines/array-manipulation.html#%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C
# =============================

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt


# copyto 复制数组
print('--- copyto ---')
a = np.array([1,2,4,5])
b = np.array([0,0,0,0])
np.copyto(b, a)             # 同构 才能复制
print(b)


# reshape 在不更改数据的情况下为数组赋予新形状
print('--- reshape ---')
a = np.arange(6).reshape((3,2))
print(a)
np.reshape(a, (2, 3))
np.reshape(np.ravel(a), (2, 3))

a = np.array([[1,2,3],[4,5,6]])
np.reshape(a, 6)                    # -1表示自主推断不指定



# ravel 返回一个连续的扁平数组
print('--- ravel ---')
x = np.array([[1,2,3],[4,5,6]])
np.ravel(x)                             # array([1, 2, 3, 4, 5, 6])


--- copyto ---
[1 2 4 5]
--- reshape ---
[[0 1]
 [2 3]
 [4 5]]
--- ravel ---


array([1, 2, 3, 4, 5, 6])

In [21]:
# moveaxis 将数组的轴移到新位置
print('--- moveaxis ---')

x = np.zeros((3, 4, 5))
np.moveaxis(x, 0, -1).shape             # (4,5,3)       将shape中0位置移动到-1位置
np.moveaxis(x, -1, 0).shape             # (5,3,4)       将shape中-1位置移动到0位置

np.transpose(x).shape                   # (5,4,3)       # 转置
np.swapaxes(x, 0, -1).shape             # (5,4,3)
np.moveaxis(x, [0, 1], [-1, -2]).shape              # (5,4,3)
np.moveaxis(x, [0, 1, 2], [-1, -2, -3]).shape       # (5,4,3)


print('--- rollaxis ---> 向后滚动指定的轴，直到其位于给定的位置')
print('--- swapaxis ---> 互换数组的两个轴')
print('--- T ---> 转置')
aa = np.ones((2,3), np.int)
aa.T
print('--- transpose ---> 排列数组尺寸')
np.transpose(aa)                # transpose 默认转置
x = np.ones((1, 2, 3))
np.transpose(x, (1, 0, 2)).shape        # (2,1,3)



--- moveaxis ---
--- rollaxis ---> 向后滚动指定的轴，直到其位于给定的位置
--- swapaxis ---> 互换数组的两个轴
--- T ---> 转置
--- transpose ---> 排列数组尺寸


(2, 1, 3)