In [1]:
# 链接数据库，获取数据

print("=== pandas读取数据库 ===")

import pandas as pd
from sqlalchemy import create_engine

USER = "waimai_dq"
PW = "iadCfu8C5xnHcl"
DB_HOST = "10.189.181.21"
DB_PORT = 5002
DB_NAME = "waimai_data_query"

# 用 sqlalchemy 构建数据库连接
connect_info = "mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8".format(USER, PW, DB_HOST, DB_PORT, DB_NAME)
print(connect_info)
engine = create_engine(connect_info)

# select id, name, git, octo_app_key, bds_mode, plus_id, plus_name, business
sql_cmd_02 = select id, name, git, octo_app_key, bds_mode, plus_id, plus_name, business from job where octo_app_key != '' limit 10"

print(sql_cmd_02)
df = pd.read_sql(sql=sql_cmd_02, con=engine, columns=['name', 'octo_app_key', 'bds_mode'])
print(df)



=== pandas读取数据库 ===
mysql+pymysql://waimai_dq:iadCfu8C5xnHcl@10.189.181.21:5002/waimai_data_query?charset=utf8
select id, name, git, octo_app_key, bds_mode, plus_id, plus_name, business from job where octo_app_key != '' limit 10
        id                                     name  \
0     4320                       banma_fe_runner_wx   
1   707259  com.sankuai.deliverygovern.appealclient   
2     4024                              banma_fe_h5   
3     5651                              banma_fe_rn   
4    60529                banma_lbs_route_algorithm   
5   257087                        banma_fe_starfire   
6  1414660    baymax-wm-billing-datamanager-service   
7  1414534       baymax-wm-billing-recovery-service   
8  1414697            baymax-wm-billing-rtc-service   
9  1414685         baymax-wm-billing-settle-service   

                                                 git  \
0  ssh://git@git.sankuai.com/bm/banma_fe_runner_w...   
1  ssh://git@git.sankuai.com/bm/banma_service_app... 

In [11]:
import numpy as np
# N维数组 ndarray
# 一个 ndarray是具有相同类型和大小的项目的（通常是固定大小的）多维容器        shape, dtype
# ndarray可以共享相同的数据; 因此在一个ndarray中进行的更改可能在另一个中可见

x = np.array([[1,2,3],[4,5,6]], np.int32)
type(x)

x.shape     # (2, 3)

x.dtype     # dtype('int32')

# 类似容器操作
x[1,2]      # 6

x           # array([[1, 2, 3],
            #        [4, 5, 6]], dtype=int32)


# 切片 生成数组视图  （ : 表示取当前维度的全部数据）
y = x[:,1]
y           # array([2, 5], dtype=int32)

y[0] = 9
y           # array([9, 5], dtype=int32)

# 此时 x 也已经跟随变动
x           # array([[1, 9, 3],
            #        [4, 5, 6]], dtype=int32)


array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [29]:
# 创建 ndarray -> [以填充方式创建]

# 返回给定形状和类型的新数组，而无需初始化条目。
nda01 = np.empty(3, np.int32)
print(nda01)

# 返回形状和类型与给定数组相同的新数组
nda02 = np.empty_like(nda01)
print(nda02)

# 返回一个二维数组，对角线上有一个，其他地方为零。(k表示第一行第k个元素为1，然后构造三角阵；当k=0时 为单位阵)
nda03 = np.eye(3, k=0)
print(nda03)

# 返回单位方阵，相当于 np.eye(n, k=0)
nda04 = np.identity(5)
print(nda04)

# 返回全部填充1的矩阵
nda05 = np.ones((3,4))
print(nda05)

# 返回全部填充0的矩阵
nda06 = np.zeros((3,4))
print(nda06)

# 返回全部填充 value 的矩阵
nda07 = np.full((3,4), 5)
print(nda07)


[0 0 0]
[0 0 0]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [31]:
# 创建 ndarray -> [从现有数据创建]

# 根据传入数据创建#
nda08 = np.array([2, 3, 5, 9.2])               # 自动upcast为 float
print(nda08)
nda09 = np.array([[1, 2], [3, 4]])             # 多维
print(nda09)




[2.  3.  5.  9.2]
[[1 2]
 [3 4]]
